name: build

on: [push, pull_request]

jobs:
  build-and-tests:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Install dependencies
        run: dotnet restore
      - name: Build and test
        run: |
          dotnet test --configuration Release --no-restore --verbosity normal NineChronicles.Headless.Tests
          dotnet test --configuration Release --no-restore --verbosity normal NineChronicles.Headless.Executable.Tests
          dotnet test --configuration Release --no-restore --verbosity normal Libplanet.Headless.Tests

  build-and-test:
    needs: [build-and-tests]
    runs-on: ubuntu-20.04
    steps:
      - run: echo done
